services:
  api:
    image: ghcr.io/cturner8/kube-mcp:dev
    build:
      context: api
      target: final
    environment:
      PUBLIC_BASE_URL: http://localhost:9000
      OIDC_ISSUER_URL: https://auth.localhost:8443
      OIDC_CLIENT_ID: 10742d2e-1f00-4b19-8412-5a2f77b53b4d
    command: [
      --allowed-origins,
      http://localhost:6274
    ]
    ports:
      - 9000:9000
