tls:
  certificates:
    - certFile: /etc/traefik/tls/localhost.pem
      keyFile: /etc/traefik/tls/localhost-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/tls/localhost.pem
        keyFile: /etc/traefik/tls/localhost-key.pem