{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-mcp.rbacName" . }}
  labels:
    {{- include "kube-mcp.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-mcp.rbacName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-mcp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
