{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-mcp.rbacName" . }}
  labels:
    {{- include "kube-mcp.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.rbac.rules }}
rules:
 {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}