name: helm

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'chart-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.1

      - name: Install Helm
        uses: azure/setup-helm@v4.3.1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package helm chart
        id: package
        run: helm package charts/kube-mcp

      - name: Push helm chart
        id: push 
        run: helm push kube-mcp-*.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --fail-on-no-commits --verify-tag --generate-notes --draft