name: test

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.1

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.13.0
      with:
        cluster-name: kube-mcp
        kubeconfig: ${{ runner.temp }}/kubeconfig

    - name: Set up Go
      uses: actions/setup-go@v6.1.0
      with:
        go-version-file: "api/go.mod"
        cache: true
        cache-dependency-path: "api/go.sum"

    - name: Build API
      working-directory: api
      run: go build -v ./...

    - name: Run Tests
      working-directory: api
      run: go test -v ./...
